name = "obsidain-mail"
main = "src/worker.js"
compatibility_date = "2024-02-01"
workers_dev = true
node_compat = true

routes = []
kv_namespaces = [{ binding = "kv4email", id = "5bc344d7fdc8404686735a327511abca" }]

[vars]
website_name= "Anonymous mail"
email_domain = '["anons.email"]'
custom_email_domain = '["ct.anons.email"]'
contact_email = "contact@anons.email"
abuse_email = "abuse@anons.email"
dropMail_email = "drop@anons.email"
